 default: &default
  adapter: mysql2
  encoding: utf8
  username: adminCThVdNL
  password: 6dCRuCg9NeeA
  pool: 5
  timeout: 5000
  socket: /tmp/mysql.sock


development:
  database: xls-demo_dev
  <<: *defaults

test:
  database: xls-demo_test
  <<: *defaults

production:
  database: xlsdemo
  <<: *defaults
