development:
 adapter: mysql2
 encoding: utf8
 database: import_export_development
 pool: 5
 username: root
 password:

test:
 adapter: mysql2
 encoding: utf8
 database: import_export_test
 pool: 5
 username: root
 password:


production:
 adapter: mysql2
 encoding: utf8
 database: xlsdemo
 pool: 5
 host: 127.0.0.1
 username: adminCThVdNL
 password: 6dCRuCg9NeeA